### ISSUE TITLE
Add metallb to flux

### ISSUE THREAD

**Issue by avnes** [avnes/flux-catalogue#8]
Plus add IP range for odin cluster:

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.200/29
  - 192.168.1.208/28
  - 192.168.1.224/28
  - 192.168.1.240/32
```
